### ISSUE TITLE
AirDrop not working

### ISSUE THREAD

**Issue by devdahyuk** [zirenxiao/LG-Gram-13Z990A-Hackintosh#1]
Hello,

I am using LG Gram 2019 Ver, and I am not able to find any devices even I have my Mac besides my LG Gram. Is it possible to get AirDrop?

Thanks,

Dahyuk

**Comment by devdahyuk** [comment]
@zirenxiao Mentioning if you hadn't been noticed about my question!

**Comment by zirenxiao** [comment]
> Hello,
> 
> I am using LG Gram 2019 Ver, and I am not able to find any devices even I have my Mac besides my LG Gram. Is it possible to get AirDrop?
> 
> Thanks,
> 
> Dahyuk

Hi Dahyuk,

Sorry for the late reply.

You may check if your Wireless card is exactly the same as my model: Intel AC-9560.

In theory, all intel cards are supported by IntelBluetoothFirmware and itlwm.

Also, macOS 11.6 is the latest version supported by this EFI. Wi-Fi and Bluetooth are disabled if you are using 12.x.

Ziren
